"""
PNG → Blender 3D Model
======================
Convert PNG images into 3D models you can open in Blender (.obj + .mtl).

Modes
-----
  voxels   – each opaque pixel becomes a colored cube (great for pixel-art / Undertale sprites)
  plane    – flat textured plane with the PNG as the material
  height   – grayscale heightmap mesh (bright = taller)

Windows usage
-------------
1. pip install Pillow
2. Double-click png_to_blender.py
   OR:  python png_to_blender.py my_sprite.png
3. Open the created .obj in Blender: File → Import → Wavefront (.obj)

Examples
--------
  python png_to_blender.py spr_toriel.png
  python png_to_blender.py spr_toriel.png --mode voxels --depth 1 --scale 0.1
  python png_to_blender.py landscape.png --mode height --depth 8
  python png_to_blender.py logo.png --mode plane
  python png_to_blender.py folder_of_pngs --batch
"""

from __future__ import annotations

import argparse
import sys
import tkinter as tk
from pathlib import Path
from tkinter import filedialog, messagebox, ttk

try:
    from PIL import Image
except ImportError:
    print("Missing Pillow. Open Command Prompt and run:")
    print("  pip install Pillow")
    input("Press Enter to exit...")
    raise SystemExit(1)

__version__ = "1.0.0"

# Faces of a unit cube (vertex index offsets into the 8 corners)
CUBE_FACES = (
    (0, 1, 2, 3),  # -Z back
    (4, 5, 6, 7),  # +Z front
    (0, 4, 7, 3),  # -X left
    (1, 5, 6, 2),  # +X right
    (3, 2, 6, 7),  # +Y top
    (0, 1, 5, 4),  # -Y bottom
)


def _cube_corners(x: float, y: float, z: float, size: float) -> list[tuple[float, float, float]]:
    s = size
    return [
        (x, y, z),
        (x + s, y, z),
        (x + s, y + s, z),
        (x, y + s, z),
        (x, y, z + s),
        (x + s, y, z + s),
        (x + s, y + s, z + s),
        (x, y + s, z + s),
    ]


def _safe_stem(path: Path) -> str:
    name = "".join(c if c.isalnum() or c in "-_" else "_" for c in path.stem)
    return name or "model"


def _rgb_key(r: int, g: int, b: int, a: int, quantize: int = 1) -> tuple[int, int, int]:
    if quantize <= 1:
        return (r, g, b)
    q = max(1, quantize)
    return ((r // q) * q, (g // q) * q, (b // q) * q)


def _write_mtl(path: Path, materials: dict[str, tuple[int, int, int]], texture: str | None = None) -> None:
    lines = ["# Generated by png_to_blender.py", ""]
    for name, (r, g, b) in materials.items():
        lines.append(f"newmtl {name}")
        lines.append(f"Kd {r / 255:.6f} {g / 255:.6f} {b / 255:.6f}")
        lines.append("Ka 0.050000 0.050000 0.050000")
        lines.append("Ks 0.000000 0.000000 0.000000")
        lines.append("d 1.0")
        lines.append("illum 1")
        if texture:
            lines.append(f"map_Kd {texture}")
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def png_to_voxels(
    image: Image.Image,
    *,
    scale: float = 1.0,
    depth: float = 1.0,
    alpha_threshold: int = 8,
    quantize: int = 1,
    merge_faces: bool = True,
) -> tuple[list[tuple[float, float, float]], list[tuple[str, list[int]]], dict[str, tuple[int, int, int]]]:
    """
    Build a voxel mesh from opaque pixels.
    Returns (vertices, faces_with_material, materials).
    faces_with_material: list of (material_name, [v1,v2,v3,v4]) — 1-based indices for OBJ.
    """
    img = image.convert("RGBA")
    w, h = img.size
    pixels = img.load()

    # Occupancy + color grid
    solid: dict[tuple[int, int], tuple[int, int, int]] = {}
    for y in range(h):
        for x in range(w):
            r, g, b, a = pixels[x, y]
            if a < alpha_threshold:
                continue
            solid[(x, y)] = _rgb_key(r, g, b, a, quantize)

    if not solid:
        raise ValueError("No opaque pixels found (image may be fully transparent).")

    materials: dict[str, tuple[int, int, int]] = {}
    color_to_mat: dict[tuple[int, int, int], str] = {}

    def mat_for(color: tuple[int, int, int]) -> str:
        if color not in color_to_mat:
            name = f"c_{color[0]:02x}{color[1]:02x}{color[2]:02x}"
            color_to_mat[color] = name
            materials[name] = color
        return color_to_mat[color]

    vertices: list[tuple[float, float, float]] = []
    faces: list[tuple[str, list[int]]] = []
    # Map corner world-key → vertex index (0-based) for welding
    corner_index: dict[tuple[int, int, int], int] = {}

    def vert(ix: int, iy: int, iz: int) -> int:
        """Grid corner → vertex index (0-based). iz is 0 or 1 (back/front of thin voxel)."""
        key = (ix, iy, iz)
        if key in corner_index:
            return corner_index[key]
        # Center the model on X/Y; Z is thickness
        vx = (ix - w / 2) * scale
        vy = ((h - iy) - h / 2) * scale  # flip Y so image up = +Y
        vz = iz * depth * scale
        corner_index[key] = len(vertices)
        vertices.append((vx, vy, vz))
        return corner_index[key]

    for (x, y), color in solid.items():
        mat = mat_for(color)
        idxs = [
            vert(x, y + 1, 0),
            vert(x + 1, y + 1, 0),
            vert(x + 1, y, 0),
            vert(x, y, 0),
            vert(x, y + 1, 1),
            vert(x + 1, y + 1, 1),
            vert(x + 1, y, 1),
            vert(x, y, 1),
        ]

        # back, front, -X, +X, +Y, -Y
        emit = [True, True, True, True, True, True]
        if merge_faces:
            emit[2] = (x - 1, y) not in solid  # -X
            emit[3] = (x + 1, y) not in solid  # +X
            emit[4] = (x, y - 1) not in solid  # +Y (image up)
            emit[5] = (x, y + 1) not in solid  # -Y (image down)

        for face_i, corners in enumerate(CUBE_FACES):
            if not emit[face_i]:
                continue
            faces.append((mat, [idxs[c] + 1 for c in corners]))

    return vertices, faces, materials


def png_to_plane(
    image: Image.Image,
    *,
    scale: float = 1.0,
) -> tuple[list[tuple[float, float, float]], list[tuple[float, float]], list[list[int]], list[list[int]]]:
    """Textured plane: vertices, uvs, faces (v), faces (vt)."""
    w, h = image.size
    width = max(1, w) * scale
    height = max(1, h) * scale
    hw, hh = width / 2, height / 2
    vertices = [
        (-hw, -hh, 0.0),
        (hw, -hh, 0.0),
        (hw, hh, 0.0),
        (-hw, hh, 0.0),
    ]
    uvs = [(0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 1.0)]
    faces_v = [[1, 2, 3, 4]]
    faces_vt = [[1, 2, 3, 4]]
    return vertices, uvs, faces_v, faces_vt


def png_to_heightmap(
    image: Image.Image,
    *,
    scale: float = 1.0,
    depth: float = 5.0,
    step: int = 1,
) -> tuple[list[tuple[float, float, float]], list[list[int]]]:
    """Grid mesh where brightness controls Z height."""
    img = image.convert("RGBA")
    w, h = img.size
    step = max(1, step)
    gray = img.convert("L")
    alpha = img.split()[-1] if image.mode in ("RGBA", "LA") else None

    xs = list(range(0, w, step))
    if xs[-1] != w - 1:
        xs.append(w - 1)
    ys = list(range(0, h, step))
    if ys[-1] != h - 1:
        ys.append(h - 1)

    index_of: dict[tuple[int, int], int] = {}
    vertices: list[tuple[float, float, float]] = []

    for iy, y in enumerate(ys):
        for ix, x in enumerate(xs):
            if alpha is not None and alpha.getpixel((x, y)) < 8:
                bright = 0
            else:
                bright = gray.getpixel((x, y)) / 255.0
            vx = (x - w / 2) * scale
            vy = ((h - 1 - y) - h / 2) * scale
            vz = bright * depth * scale
            index_of[(ix, iy)] = len(vertices)
            vertices.append((vx, vy, vz))

    faces: list[list[int]] = []
    for iy in range(len(ys) - 1):
        for ix in range(len(xs) - 1):
            a = index_of[(ix, iy)] + 1
            b = index_of[(ix + 1, iy)] + 1
            c = index_of[(ix + 1, iy + 1)] + 1
            d = index_of[(ix, iy + 1)] + 1
            faces.append([a, b, c, d])
    return vertices, faces


def write_obj_voxels(
    out_obj: Path,
    vertices: list[tuple[float, float, float]],
    faces: list[tuple[str, list[int]]],
    materials: dict[str, tuple[int, int, int]],
) -> Path:
    mtl_name = out_obj.with_suffix(".mtl").name
    _write_mtl(out_obj.with_suffix(".mtl"), materials)
    lines = [
        "# Generated by png_to_blender.py",
        f"mtllib {mtl_name}",
        f"# vertices: {len(vertices)}  faces: {len(faces)}",
        "",
    ]
    for x, y, z in vertices:
        lines.append(f"v {x:.6f} {y:.6f} {z:.6f}")
    lines.append("")

    current = None
    for mat, idxs in faces:
        if mat != current:
            lines.append(f"usemtl {mat}")
            current = mat
        lines.append("f " + " ".join(str(i) for i in idxs))

    out_obj.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out_obj


def write_obj_plane(
    out_obj: Path,
    image_path: Path,
    vertices,
    uvs,
    faces_v,
    faces_vt,
) -> Path:
    # Copy / reference texture next to obj
    tex_name = image_path.name
    dest_tex = out_obj.parent / tex_name
    if dest_tex.resolve() != image_path.resolve():
        dest_tex.write_bytes(image_path.read_bytes())

    materials = {"textured": (255, 255, 255)}
    _write_mtl(out_obj.with_suffix(".mtl"), materials, texture=tex_name)

    lines = [
        "# Generated by png_to_blender.py (textured plane)",
        f"mtllib {out_obj.with_suffix('.mtl').name}",
        "",
    ]
    for x, y, z in vertices:
        lines.append(f"v {x:.6f} {y:.6f} {z:.6f}")
    for u, v in uvs:
        lines.append(f"vt {u:.6f} {v:.6f}")
    lines.append("usemtl textured")
    for fv, ft in zip(faces_v, faces_vt):
        lines.append("f " + " ".join(f"{v}/{t}" for v, t in zip(fv, ft)))
    out_obj.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out_obj


def write_obj_height(out_obj: Path, vertices, faces) -> Path:
    materials = {"height": (180, 180, 180)}
    _write_mtl(out_obj.with_suffix(".mtl"), materials)
    lines = [
        "# Generated by png_to_blender.py (heightmap)",
        f"mtllib {out_obj.with_suffix('.mtl').name}",
        "",
    ]
    for x, y, z in vertices:
        lines.append(f"v {x:.6f} {y:.6f} {z:.6f}")
    lines.append("usemtl height")
    for face in faces:
        lines.append("f " + " ".join(str(i) for i in face))
    out_obj.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out_obj


def convert_png(
    png_path: str | Path,
    out_dir: str | Path | None = None,
    *,
    mode: str = "voxels",
    scale: float = 0.1,
    depth: float = 1.0,
    alpha_threshold: int = 8,
    quantize: int = 1,
    height_step: int = 1,
) -> Path:
    """Convert one PNG to an .obj (and .mtl) Blender can import. Returns .obj path."""
    png_path = Path(png_path)
    if not png_path.is_file():
        raise FileNotFoundError(f"PNG not found: {png_path}")

    out_dir = Path(out_dir) if out_dir else png_path.parent
    out_dir.mkdir(parents=True, exist_ok=True)
    out_obj = out_dir / f"{_safe_stem(png_path)}_{mode}.obj"

    image = Image.open(png_path)
    mode = mode.lower().strip()

    if mode == "voxels":
        vertices, faces, materials = png_to_voxels(
            image,
            scale=scale,
            depth=depth,
            alpha_threshold=alpha_threshold,
            quantize=quantize,
        )
        write_obj_voxels(out_obj, vertices, faces, materials)
    elif mode == "plane":
        vertices, uvs, faces_v, faces_vt = png_to_plane(image, scale=scale)
        write_obj_plane(out_obj, png_path, vertices, uvs, faces_v, faces_vt)
    elif mode in {"height", "heightmap"}:
        vertices, faces = png_to_heightmap(
            image, scale=scale, depth=depth, step=height_step
        )
        write_obj_height(out_obj, vertices, faces)
    else:
        raise ValueError(f"Unknown mode: {mode!r}. Use voxels, plane, or height.")

    return out_obj


def convert_many(paths: list[Path], **kwargs) -> list[Path]:
    results = []
    for path in paths:
        obj = convert_png(path, **kwargs)
        results.append(obj)
        print(f"OK  {path.name} → {obj}")
    return results


# ----- simple windowed UI -----


class ConverterApp(tk.Tk):
    def __init__(self) -> None:
        super().__init__()
        self.title("PNG → Blender 3D Model")
        self.geometry("520x420")
        self.minsize(480, 380)

        self.png_var = tk.StringVar()
        self.out_var = tk.StringVar()
        self.mode_var = tk.StringVar(value="voxels")
        self.scale_var = tk.StringVar(value="0.1")
        self.depth_var = tk.StringVar(value="1.0")
        self.status_var = tk.StringVar(value="Pick a PNG, then click Convert.")

        pad = {"padx": 12, "pady": 6}
        frm = ttk.Frame(self, padding=12)
        frm.pack(fill="both", expand=True)

        ttk.Label(frm, text="PNG → Blender (.obj)", font=("Segoe UI", 14, "bold")).pack(
            anchor="w", **pad
        )
        ttk.Label(
            frm,
            text="Creates a .obj + .mtl you can import in Blender.",
            foreground="#555",
        ).pack(anchor="w", padx=12)

        row = ttk.Frame(frm)
        row.pack(fill="x", **pad)
        ttk.Entry(row, textvariable=self.png_var).pack(side="left", fill="x", expand=True)
        ttk.Button(row, text="Browse PNG…", command=self.browse_png).pack(side="left", padx=4)

        row2 = ttk.Frame(frm)
        row2.pack(fill="x", **pad)
        ttk.Entry(row2, textvariable=self.out_var).pack(side="left", fill="x", expand=True)
        ttk.Button(row2, text="Output folder…", command=self.browse_out).pack(side="left", padx=4)

        opts = ttk.LabelFrame(frm, text="Options", padding=8)
        opts.pack(fill="x", **pad)

        ttk.Label(opts, text="Mode").grid(row=0, column=0, sticky="w")
        ttk.Combobox(
            opts,
            textvariable=self.mode_var,
            values=["voxels", "plane", "height"],
            state="readonly",
            width=12,
        ).grid(row=0, column=1, sticky="w", padx=6)

        ttk.Label(opts, text="Scale").grid(row=1, column=0, sticky="w")
        ttk.Entry(opts, textvariable=self.scale_var, width=10).grid(row=1, column=1, sticky="w", padx=6)

        ttk.Label(opts, text="Depth").grid(row=2, column=0, sticky="w")
        ttk.Entry(opts, textvariable=self.depth_var, width=10).grid(row=2, column=1, sticky="w", padx=6)

        ttk.Label(
            opts,
            text="voxels = pixel cubes  ·  plane = flat image  ·  height = grayscale bump",
            foreground="#666",
        ).grid(row=3, column=0, columnspan=2, sticky="w", pady=(8, 0))

        ttk.Button(frm, text="Convert to Blender model", command=self.convert).pack(
            fill="x", **pad
        )
        ttk.Button(frm, text="Convert folder of PNGs…", command=self.convert_folder).pack(
            fill="x", padx=12, pady=2
        )

        ttk.Label(frm, textvariable=self.status_var, wraplength=460).pack(anchor="w", **pad)

        tip = (
            "In Blender: File → Import → Wavefront (.obj)\n"
            "Select the .obj file this program creates."
        )
        ttk.Label(frm, text=tip, foreground="#333").pack(anchor="w", padx=12, pady=8)

    def browse_png(self) -> None:
        path = filedialog.askopenfilename(
            title="Select PNG",
            filetypes=[("PNG images", "*.png"), ("All images", "*.png;*.jpg;*.jpeg;*.webp"), ("All files", "*.*")],
        )
        if path:
            self.png_var.set(path)
            if not self.out_var.get():
                self.out_var.set(str(Path(path).parent))

    def browse_out(self) -> None:
        path = filedialog.askdirectory(title="Output folder")
        if path:
            self.out_var.set(path)

    def _params(self) -> dict:
        try:
            scale = float(self.scale_var.get())
            depth = float(self.depth_var.get())
        except ValueError as exc:
            raise ValueError("Scale and Depth must be numbers.") from exc
        return {
            "mode": self.mode_var.get(),
            "scale": scale,
            "depth": depth,
            "out_dir": self.out_var.get() or None,
        }

    def convert(self) -> None:
        png = self.png_var.get().strip()
        if not png:
            messagebox.showwarning("No file", "Choose a PNG first.")
            return
        try:
            params = self._params()
            out_dir = params.pop("out_dir")
            obj = convert_png(png, out_dir, **params)
            self.status_var.set(f"Saved: {obj}\nAlso wrote: {obj.with_suffix('.mtl')}")
            messagebox.showinfo(
                "Done",
                f"Created:\n{obj}\n\nOpen it in Blender:\nFile → Import → Wavefront (.obj)",
            )
        except Exception as exc:
            messagebox.showerror("Conversion failed", str(exc))
            self.status_var.set(f"Error: {exc}")

    def convert_folder(self) -> None:
        folder = filedialog.askdirectory(title="Folder with PNG files")
        if not folder:
            return
        pngs = sorted(Path(folder).glob("*.png"))
        if not pngs:
            messagebox.showwarning("No PNGs", "No .png files in that folder.")
            return
        try:
            params = self._params()
            out_dir = params.pop("out_dir") or folder
            results = convert_many(pngs, out_dir=out_dir, **params)
            self.status_var.set(f"Converted {len(results)} files → {out_dir}")
            messagebox.showinfo("Done", f"Converted {len(results)} PNGs to .obj models.")
        except Exception as exc:
            messagebox.showerror("Conversion failed", str(exc))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Convert PNG images into Blender-ready 3D models (.obj)"
    )
    parser.add_argument("input", nargs="?", help="PNG file or folder")
    parser.add_argument("-o", "--out", help="Output folder")
    parser.add_argument(
        "-m",
        "--mode",
        choices=["voxels", "plane", "height"],
        default="voxels",
        help="Conversion mode (default: voxels)",
    )
    parser.add_argument("--scale", type=float, default=0.1, help="Size of one pixel in Blender units")
    parser.add_argument("--depth", type=float, default=1.0, help="Voxel / height thickness")
    parser.add_argument("--alpha", type=int, default=8, help="Alpha cutoff 0-255")
    parser.add_argument("--quantize", type=int, default=1, help="Color quantization step")
    parser.add_argument("--step", type=int, default=1, help="Heightmap sampling step")
    parser.add_argument("--batch", action="store_true", help="Convert all PNGs in a folder")
    parser.add_argument("--gui", action="store_true", help="Open the windowed converter")
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    args = parser.parse_args(argv)

    if args.gui or not args.input:
        # No args → open GUI (friendly for double-click on Windows)
        app = ConverterApp()
        app.mainloop()
        return 0

    path = Path(args.input)
    kwargs = dict(
        out_dir=args.out,
        mode=args.mode,
        scale=args.scale,
        depth=args.depth,
        alpha_threshold=args.alpha,
        quantize=args.quantize,
        height_step=args.step,
    )

    try:
        if path.is_dir() or args.batch:
            folder = path if path.is_dir() else path.parent
            pngs = sorted(folder.glob("*.png"))
            if not pngs:
                print(f"No PNG files in {folder}", file=sys.stderr)
                return 1
            convert_many(pngs, **kwargs)
        else:
            obj = convert_png(path, **kwargs)
            print(f"Created {obj}")
            print(f"Material {obj.with_suffix('.mtl')}")
            print("Blender: File → Import → Wavefront (.obj)")
    except Exception as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
